version: '3.6'
services:
  base:
    build: .
    image: base
    stdin_open: true
    tty: true    
    command: ${COMPOSE_COMMAND:-bash}
    env_file:
      - configs.env
    volumes:
      - .:/app
      # - /var/run/docker.sock:/var/run/docker.sock #Needed so a docker container can be run from inside a docker container
      - ~/.aws/:/root/.aws:ro
    ports:
      - "3000:3000"