name: CI

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - bugfix/*
      - feature/*

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

# env:
#   IMAGE_NAME: go-hello-world

jobs:

  build:
    
    runs-on: ubuntu-latest
    # if: github.event_name == 'push'

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Prep Configs
      run: | 
        make _prep-env-ci
        cat configs.env

    - name: Install
      run: |
        make install

    - name: Frontend Unit Tests
      run: make test-frontend
      
    #Need to get tests hitting API to work
    # - name: Local e2e test
    #   run: | 
    #     make run > /dev/null 2>&1 & 
    #     make test-e2e-ci

    - name: Build
      run: make ci
    
    - name: Infra Synth
      run: make synth

    - name: Infra Unit Tests
      run: make test-infra

    - name: Backend Unit Tests
      run: make test-backend

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}