name: CI

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

# env:
#   IMAGE_NAME: go-hello-world

jobs:

  build:
    
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Install
      run: make install

    - name: Tests
      run: make test-ci
      
    - name: Build
      run: make ci

    # - name: Run the Go package locally (detached)
    #   run: make run