name: CI

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - bugfix/*
      - feature/*

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

# env:
#   IMAGE_NAME: go-hello-world

jobs:

  build:
    
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Install
      run: |
        sudo chown -R 1001:0 "/.npm"
        make install

    - name: Frontend Unit Tests
      run: make test-frontend
      
    - name: Local e2e test
      run: | 
        make run-frontend-daemon
        make test-e2e

    - name: Build
      run: make ci
    
    - name: Infra Synth
      run: make synth

    # - name: Infra Unit Tests
    #   run: make test-infra

    # - name: Run the Go package locally (detached)
    #   run: make run