name: CI

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - bugfix/*
      - feature/*

  # Run tests for any PRs.
  pull_request:
  
jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }} #Include package lock in name so on change cache is invalidated
        restore-keys: npm-

    - name: Install
      run: |
        make install